name = "cloudmember-alvintools"
main = "_worker.js"
compatibility_date = "2026-04-20"
account_id = "b945ec26283730ad8c450205350398f8"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "alvintools"
database_id = "65319e03-8e26-41e2-b438-7d9ed66a4e4d"

[triggers]
crons = ["0 * * * *"] # Ini artinya cek otomatis SETIAP JAM
