name = "cloudmember-client"
main = "_worker.js"
compatibility_date = "2026-06-04"

[assets]
directory = "."
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "alvintools"
database_id = "65319e03-8e26-41e2-b438-7d9ed66a4e4d"

[vars]
INSTALLATION_MODE = "master"
MASTER_UPDATE_URL = "https://domain-kamu.com/version.json"
LICENSE_SERVER_URL = "https://domain-kamu.com/"
ADMIN_SESSION_SECRET = "alvinbelajarsemangat-x7K9pQ2mZ4"
CRON_TOKEN = "crn_8xK2mP9qL4wZ7vN1tR6sYcB3"

[triggers]
crons = ["0 * * * *"]
